"""added embeddings for questionbank, Learning material and update db

Revision ID: 6547c98ed1f2
Revises: 7080861f10de
Create Date: 2025-01-01 19:28:55.461185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6547c98ed1f2'
down_revision = '7080861f10de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.PickleType(), nullable=True))

    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
