"""added status column for questionbank and update db

Revision ID: 71086de338f5
Revises: 955abecd7f07
Create Date: 2024-12-21 14:36:55.535835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71086de338f5'
down_revision = '955abecd7f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
