"""added percentage and max_attempts and update db

Revision ID: 955abecd7f07
Revises: 016d9b10fe44
Create Date: 2024-12-20 21:47:48.854644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '955abecd7f07'
down_revision = '016d9b10fe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_bank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('topics', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('technologies', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('num_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_url_excel', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('file_url_pdf', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_bank_pkey'),
    sa.UniqueConstraint('transaction_id', name='question_bank_transaction_id_key')
    )
    # ### end Alembic commands ###
