"""added Learning material detail in feedback table and update db

Revision ID: 9bbe3d3545e8
Revises: 6547c98ed1f2
Create Date: 2025-01-01 23:25:53.474133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbe3d3545e8'
down_revision = '6547c98ed1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
