"""added estimated_hours column for questionbank and update db

Revision ID: b6eaf17b5f44
Revises: 71086de338f5
Create Date: 2024-12-21 22:41:42.100212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eaf17b5f44'
down_revision = '71086de338f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    # ### end Alembic commands ###
